# -*- coding: utf-8 -*-
"""parsing_in _python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYm5-NffCtyfGTNgsRQWJMalGQGxdWSs
"""

import numpy as np

a = np.array ([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
a

b = a[2:4, 1:2]
b