# -*- coding: utf-8 -*-
"""static website scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYm5-NffCtyfGTNgsRQWJMalGQGxdWSs
"""

import numpy as np

a = np.array ([[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12],
               [13,14,15,16]])
a

b = a[2:4, 1:2]
b

a[1, :]

a[a>10]

"""# ***Data Types***"""

x = np.array([1, 2])
print(x.dtype)

"""# ***Only Type***"""

type(x)

x = np.array([1, 2], dtype=np.float64)
print(x, x.dtype)

x.dtype

x = np.array([[1,2], [3,4]], dtype = np.float64)
y = np.array([[1,2], [3,4]], dtype = np.float64)
print(x)

x, x.shape

x.T, x.T.shape

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(x)
print(y)

"""# ***Broadcasting***"""

x = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
y = [[1, 0, 1]]
p = x+y
print(p)

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 0, 1])
p = x + y
p

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = np.array([1, 2, 3])
p = x.T + y
p

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[-1, -2]])
p = x.T + y
p

webpage = "https://en.wikipedia.org/wiki/Red_states_and_blue_states"

import requests
import bs4
import pandas as pd

"""Mozilla/5.0

Historical label for compatibility (almost all browsers include this)

(Windows NT 10.0; Win64; x64)

Says you're using:

Windows 10

64-bit system

AppleWebKit/537.36

Browser engine (used by Chrome, Safari, etc.)

(KHTML, like Gecko)

Compatibility note for rendering engines

Chrome/120.0.0.0

Pretends you're using Chrome version 120

Safari/537.36

Another compatibility tag
"""

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/120.0.0.0 Safari/537.36"
}

web_page = bs4.BeautifulSoup(requests.get(webpage, {}, headers=headers).text, 'lxml')

web_page

tables = web_page.find_all(name='table', attrs={'class': 'wikitable'})
tables

table = tables[0]
table

data = [[cell.get_text(strip=True) for cell in cells]
        for row in table.find_all("tr")
        for cells in [row.find_all(["td", "th"])] ]

data

df = pd.DataFrame(data)
df